### ISSUE TITLE
On windows the action can not be run: "No such file or directory: 'requirements.txt'"

### ISSUE THREAD

**Issue by SanBen** [Soumeh/Auto-Versioning#2]
If I use the action on a Windows image it fails with the following error:
> Run python -m pip install -r requirements.txt
    ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
    Error: Process completed with exit code 1.

With the following yaml:

``` yaml
name: build
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get Versioning Data
        id: versioning
        uses: Soumeh/Auto-Versioning@main
```

**Comment by SanBen** [comment]
There is a bug in the action.yml...
Apparently the ```${{ github.action_path }}``` variable does not work on Windows and the ```$GITHUB_ACTION_PATH``` should be used instead:

https://github.com/orgs/community/discussions/25910

This would probably fix the issue and make it work cross-platform

**Comment by SanBen** [comment]
For anybody with the same issue, there is a fork that can be used as a workaround for the moment:

example yaml:
``` yaml
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get Versioning Data
        id: versioning
        uses: oxygen-dioxide/Auto-Versioning@main
```

It will most likely only work on Windows though ☹️ since it just switched the shell being used and didn't solve the actual problem of the path containing the wrong slashes
